### ISSUE TITLE
Replaced with different tasks

### ISSUE THREAD

**Issue by hannahwood** [hannahwood/stackstore#34]

**Comment by seanbert4** [comment]
This will include :

- Creating a new admin-only "users" state, which shows a clickable list of all users. The admin can select a user and will be taken to that user's page

- Creating an admin-only view of a single-user page which enables the admin to:
     - Change the user type (upgrade to Admin, for example)
     - Delete the user, possibly with some sort of "Are you sure?" confirmation message, possibly with some sort of "The user was deleted" notification upon successful deletion, and then redirect the admin to the admin-only "users" state
     - "Trigger a password reset for a user" (this is right from the requirements)
