### ISSUE TITLE
Create "Checkout" page (front-end)

### ISSUE THREAD

**Issue by seanbert4** [hannahwood/stackstore#36]
### DON'T WORK ON THIS UNTIL TASK #46 IS FINISHED
- Build form that pre-populates the fields (for name, e-mail, shipping/billing address) but enables the user to edit those fields before checking out (however, logged-in users should not be able to edit their e-mail address).
- Use the Stripe library (see 'Extra Features' section in the workshop requirements) to simulate the CC transaction

**Comment by zausnerd** [comment]
What if upon clicking 'checkout', we show some previously hide elements that include shipping address, pay with card, etc?

**Comment by seanbert4** [comment]
I like that idea! There's just a form that gets ng-show(n) when the user selects "checkout." Sounds good to me.
